Fix errors when two project documents share a key
keys are not unique, so we can't disambiguate documents that way.
This changes s3-id to be the unique id.

Fixes this error:

java.lang.AssertionError: Assert failed: find-one - multiple results from query
(pred value)
 at sysrev.util$assert_pred.invokeStatic (util.cljc:68)
    sysrev.util$assert_pred.invoke (util.cljc:58)
    sysrev.db.queries$find_one.invokeStatic (queries.clj:346)
    sysrev.db.queries$find_one.doInvoke (queries.clj:330)
    clojure.lang.RestFn.invoke (RestFn.java:494)
    sysrev.file.document$lookup_document_file.invokeStatic (document.clj:18)
    sysrev.file.document$lookup_document_file.invoke (document.clj:16)
    sysrev.web.routes.project$fn__83515.invokeStatic (project.clj:702)
    sysrev.web.routes.project/fn (project.clj:697)
    compojure.core$wrap_response$fn__76268.invoke (core.clj:158)
    compojure.core$pre_init$fn__76321.invoke (core.clj:333)
    sysrev.web.app$wrap_sr_context_request$fn__46534.invoke (app.clj:248)
    sysrev.web.app$wrap_sysrev_response$fn__46512.invoke (app.clj:180)
    sysrev.web.app$wrap_add_anti_forgery_token$fn__46454.invoke (app.clj:83)
    sysrev.web.app$wrap_no_cache$fn__46449.invoke (app.clj:77)
    sysrev.web.app$wrap_robot_noindex$fn__46469.invoke (app.clj:106)
    sysrev.web.app$wrap_log_request$fn__46465.invoke (app.clj:102)
    sysrev.web.app$wrap_dynamic_vars$fn__46528.invoke (app.clj:235)
    sysrev.web.app$wrap_sr_context$fn__46531.invoke (app.clj:242)
    sysrev.web.core$wrap_exit_on_full_connection_pool$fn__85010.invoke (core.clj:74)